<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title>MariaDB Knowledge Base Comments for: maxscale fee filter error</title><link>https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/feed/</link><description></description><atom:link href="https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/feed/" rel="self"></atom:link><language>en-us</language><lastBuildDate>Tue, 13 Jun 2023 02:11:14 +0000</lastBuildDate><item><title>Re: maxscale fee filter error</title><link>https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/1945</link><description>&lt;p&gt;That is probably caused by the default behavior of not allowing root user to be used. If you want to enable it, please read the &lt;code&gt;enable_root_user&lt;/code&gt; description in the Service section of the configuration guide:
&lt;a href="https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale/maxscale-configuration-usage-scenarios/"&gt;https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale/maxscale-configuration-usage-scenarios/&lt;/a&gt;&lt;/p&gt;
</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Markus Mäkelä</dc:creator><guid>https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/1945</guid></item><item><title>Re: maxscale fee filter error</title><link>https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/1943</link><description>&lt;p&gt;Thanks, maxscale started correctly.
However, whenever I tried to connect maxscale authentication fails.
Each mysql server I can connect as root remotely.&lt;/p&gt;
&lt;p&gt;Error log is as follows;&lt;/p&gt;
&lt;p&gt;[root@localhost maxscale]# tail -f error1.log 
-----------------------------------------------------------------------
---	Logging is enabled.
2016-01-26 18:27:24   MaxScale received signal SIGTERM. Exiting.
2016-01-26 18:27:24   MaxScale is shut down.	
-----------------------------------------------------------------------&lt;/p&gt;
&lt;p&gt;MariaDB Corporation MaxScale	/var/log/maxscale/error1.log Tue Jan 26 18:27:36 2016
-----------------------------------------------------------------------
---	Logging is enabled.
2016-01-26 18:28:24   Data Service: login attempt for user 'root', authentication failed.&lt;/p&gt;
</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">상봉 이</dc:creator><guid>https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/1943</guid></item><item><title>Re: maxscale fee filter error</title><link>https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/1942</link><description>&lt;p&gt;The name of the module is 'readconnroute' instead of 'readconnrouter'.&lt;/p&gt;
</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Markus Mäkelä</dc:creator><guid>https://mariadb.com/kb/en/maxscale-fee-filter-error/+comments/1942</guid></item></channel></rss>